name: Angular CI/CD with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
      - name: Checkout source
        uses: actions/checkout@v3
     
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build --prod
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/merchant-ui:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into the instance and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.207.248.164 << 'EOF'
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker-compose -f /docker-compose.yml pull
           docker-compose -f /docker-compose.yml up -d
          EOF
