name: Angular CI/CD with Docker

on:
  push:
    branches: [ main ] # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
      - name: Checkout source
        uses: actions/checkout@v3
     
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build --prod # Adjust this command based on your Angular project setup
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/merchant-ui .
      
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/merchant-ui:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli 
  
      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region your-aws-region
  
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
 
      - name: Pull image from Docker registry
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/merchant-ui:latest
 
      - name: Stop and remove old container (if exists)
        run: docker rm -f merchant-ui-container || true
 
      - name: Run Docker container
        run: docker run -d -p 80:8080 --name merchant-ui-container ${{ secrets.DOCKER_USERNAME }}/merchant-ui:latest
 